# jdk
FROM openjdk:8-jre-alpine

# maintainer
LABEL maintainer="xavier.mires@gmail.com"

# volume
VOLUME d:/docker-volume

# ports
EXPOSE 8080

# app location
ARG APP=target/classcompiler-springboot-1.0.0-SNAPSHOT.jar

# add app
ADD ${APP} classcompiler-springboot.jar

# add libs
ADD target/lib /lib

# go polar bears
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar classcompiler-springboot.jar"]